services:
  web:
    image: web-app
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@${MONGODB_URI:-mongo:27017}/
  
  mongo:
    image: mongo:${MONGODB_VERSION:-8.0}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-password}
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 60s
      retries: 5
      start_period: 60s
    volumes:
      - mongo_data:/data/db:rw

### Mongo docker login command ###
# mongosh -u "AdminLogin" -p "AdminPassword" --authenticationDatabase "admin"
  

volumes:
  mongo_data: