# Development environment override
services:
  web-app:
    build:
      context: ${APP_DIRNAME:-./nuxt-app}              # change dir name
      target: dev
    volumes:
      - ${APP_DIRNAME:-./nuxt-app}:/app                # change dir name
      - /app/node_modules
      - /app/.nuxt
    stdin_open: true                # Needed for HMR
    environment:
      CHOKIDAR_USEPOLLING: true    # Needed for HMR
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
