# Production environment override
services:
  nuxt-app:
    build:
      context: ${APP_DIRNAME:-./nuxt-app}   #change dir name
      target: prod

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
